
package isos.iesd.servectorcli;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransactionManager", targetNamespace = "http://transactionmanager.iesd.isos/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransactionManager {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "canExecuteTransaction", targetNamespace = "http://transactionmanager.iesd.isos/", className = "isos.iesd.servectorcli.CanExecuteTransaction")
    @ResponseWrapper(localName = "canExecuteTransactionResponse", targetNamespace = "http://transactionmanager.iesd.isos/", className = "isos.iesd.servectorcli.CanExecuteTransactionResponse")
    @Action(input = "http://transactionmanager.iesd.isos/TransactionManager/canExecuteTransactionRequest", output = "http://transactionmanager.iesd.isos/TransactionManager/canExecuteTransactionResponse")
    public boolean canExecuteTransaction(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
