
package isos.iesd.transactionmanager;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "VectorService", targetNamespace = "http://servector.iesd.isos/", wsdlLocation = "http://localhost:2060/Vector?wsdl")
public class VectorService
    extends Service
{

    private static final URL VECTORSERVICE_WSDL_LOCATION;
    private static final WebServiceException VECTORSERVICE_EXCEPTION;
    private static final QName VECTORSERVICE_QNAME = new QName("http://servector.iesd.isos/", "VectorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:2060/Vector?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VECTORSERVICE_WSDL_LOCATION = url;
        VECTORSERVICE_EXCEPTION = e;
    }

    public VectorService() {
        super(__getWsdlLocation(), VECTORSERVICE_QNAME);
    }

    public VectorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VECTORSERVICE_QNAME, features);
    }

    public VectorService(URL wsdlLocation) {
        super(wsdlLocation, VECTORSERVICE_QNAME);
    }

    public VectorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VECTORSERVICE_QNAME, features);
    }

    public VectorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VectorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IVector
     */
    @WebEndpoint(name = "VectorPort")
    public IVector getVectorPort() {
        return super.getPort(new QName("http://servector.iesd.isos/", "VectorPort"), IVector.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IVector
     */
    @WebEndpoint(name = "VectorPort")
    public IVector getVectorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servector.iesd.isos/", "VectorPort"), IVector.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VECTORSERVICE_EXCEPTION!= null) {
            throw VECTORSERVICE_EXCEPTION;
        }
        return VECTORSERVICE_WSDL_LOCATION;
    }

}
