FROM openjdk:21-jdk-slim

RUN apt-get update && apt-get install -y iproute2 iputils-ping && apt-get clean

WORKDIR /app

COPY Manager-1.0-jar-with-dependencies.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
