# obtain the base Linux image with Java runtime
FROM eclipse-temurin:21-jre-jammy

# Place java executable at /usr/app
COPY ./target/SerVectorOPE-0.1.0-jar-with-dependencies.jar /usr/app/

# The listening port
EXPOSE 2060

# Starts the SerVector service
CMD ["java","-jar","/usr/app/SerVectorOPE-0.1.0-jar-with-dependencies.jar"]
