
package tm;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ITM", targetNamespace = "http://tmserver")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITM {


    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendTransaction", targetNamespace = "http://tmserver", className = "tm.SendTransaction")
    @ResponseWrapper(localName = "sendTransactionResponse", targetNamespace = "http://tmserver", className = "tm.SendTransactionResponse")
    @Action(input = "http://tmserver/ITM/sendTransactionRequest", output = "http://tmserver/ITM/sendTransactionResponse")
    public boolean sendTransaction(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "check", targetNamespace = "http://tmserver", className = "tm.Check")
    @ResponseWrapper(localName = "checkResponse", targetNamespace = "http://tmserver", className = "tm.CheckResponse")
    @Action(input = "http://tmserver/ITM/checkRequest", output = "http://tmserver/ITM/checkResponse")
    public int check(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
