
package tm;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ITM", targetNamespace = "http://tmserver")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITM {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "check", targetNamespace = "http://tmserver", className = "tm.Check")
    @ResponseWrapper(localName = "checkResponse", targetNamespace = "http://tmserver", className = "tm.CheckResponse")
    @Action(input = "http://tmserver/ITM/checkRequest", output = "http://tmserver/ITM/checkResponse")
    public int check(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
