
package tm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "TMService", targetNamespace = "http://tm/", wsdlLocation = "http://localhost:2060/TM?wsdl")
public class TMService
    extends Service
{

    private static final URL TMSERVICE_WSDL_LOCATION;
    private static final WebServiceException TMSERVICE_EXCEPTION;
    private static final QName TMSERVICE_QNAME = new QName("http://tm/", "TMService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:2060/TM?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TMSERVICE_WSDL_LOCATION = url;
        TMSERVICE_EXCEPTION = e;
    }

    public TMService() {
        super(__getWsdlLocation(), TMSERVICE_QNAME);
    }

    public TMService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TMSERVICE_QNAME, features);
    }

    public TMService(URL wsdlLocation) {
        super(wsdlLocation, TMSERVICE_QNAME);
    }

    public TMService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TMSERVICE_QNAME, features);
    }

    public TMService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TMService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ITM
     */
    @WebEndpoint(name = "TMPort")
    public ITM getTMPort() {
        return super.getPort(new QName("http://tm/", "TMPort"), ITM.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITM
     */
    @WebEndpoint(name = "TMPort")
    public ITM getTMPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tm/", "TMPort"), ITM.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TMSERVICE_EXCEPTION!= null) {
            throw TMSERVICE_EXCEPTION;
        }
        return TMSERVICE_WSDL_LOCATION;
    }

}
