
package isos.iesd.servector;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IVector", targetNamespace = "http://isos.iesd.servectorserver")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IVector {


    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @RequestWrapper(localName = "write", targetNamespace = "http://isos.iesd.servectorserver", className = "isos.iesd.servector.Write")
    @ResponseWrapper(localName = "writeResponse", targetNamespace = "http://isos.iesd.servectorserver", className = "isos.iesd.servector.WriteResponse")
    @Action(input = "http://isos.iesd.servectorserver/IVector/writeRequest", output = "http://isos.iesd.servectorserver/IVector/writeResponse")
    public void write(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "read", targetNamespace = "http://isos.iesd.servectorserver", className = "isos.iesd.servector.Read")
    @ResponseWrapper(localName = "readResponse", targetNamespace = "http://isos.iesd.servectorserver", className = "isos.iesd.servector.ReadResponse")
    @Action(input = "http://isos.iesd.servectorserver/IVector/readRequest", output = "http://isos.iesd.servectorserver/IVector/readResponse")
    public int read(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "invariantCheck", targetNamespace = "http://isos.iesd.servectorserver", className = "isos.iesd.servector.InvariantCheck")
    @ResponseWrapper(localName = "invariantCheckResponse", targetNamespace = "http://isos.iesd.servectorserver", className = "isos.iesd.servector.InvariantCheckResponse")
    @Action(input = "http://isos.iesd.servectorserver/IVector/invariantCheckRequest", output = "http://isos.iesd.servectorserver/IVector/invariantCheckResponse")
    public String invariantCheck();

}
