
package tm;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IServiceVector", targetNamespace = "http://servicevectorserver")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IServiceVector {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkServiceVector", targetNamespace = "http://servicevectorserver", className = "tm.CheckServiceVector")
    @ResponseWrapper(localName = "checkServiceVectorResponse", targetNamespace = "http://servicevectorserver", className = "tm.CheckServiceVectorResponse")
    @Action(input = "http://servicevectorserver/IServiceVector/checkServiceVectorRequest", output = "http://servicevectorserver/IServiceVector/checkServiceVectorResponse")
    public int checkServiceVector(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
