
package tm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ServiceVectorService", targetNamespace = "http://servicevector/", wsdlLocation = "http://localhost:2061/ServiceVector?wsdl")
public class ServiceVectorService
    extends Service
{

    private static final URL SERVICEVECTORSERVICE_WSDL_LOCATION;
    private static final WebServiceException SERVICEVECTORSERVICE_EXCEPTION;
    private static final QName SERVICEVECTORSERVICE_QNAME = new QName("http://servicevector/", "ServiceVectorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:2061/ServiceVector?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEVECTORSERVICE_WSDL_LOCATION = url;
        SERVICEVECTORSERVICE_EXCEPTION = e;
    }

    public ServiceVectorService() {
        super(__getWsdlLocation(), SERVICEVECTORSERVICE_QNAME);
    }

    public ServiceVectorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEVECTORSERVICE_QNAME, features);
    }

    public ServiceVectorService(URL wsdlLocation) {
        super(wsdlLocation, SERVICEVECTORSERVICE_QNAME);
    }

    public ServiceVectorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEVECTORSERVICE_QNAME, features);
    }

    public ServiceVectorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceVectorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServiceVector
     */
    @WebEndpoint(name = "ServiceVectorPort")
    public IServiceVector getServiceVectorPort() {
        return super.getPort(new QName("http://servicevector/", "ServiceVectorPort"), IServiceVector.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiceVector
     */
    @WebEndpoint(name = "ServiceVectorPort")
    public IServiceVector getServiceVectorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicevector/", "ServiceVectorPort"), IServiceVector.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEVECTORSERVICE_EXCEPTION!= null) {
            throw SERVICEVECTORSERVICE_EXCEPTION;
        }
        return SERVICEVECTORSERVICE_WSDL_LOCATION;
    }

}
