
package tm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ServiceVector2Service", targetNamespace = "http://servicevector2/", wsdlLocation = "http://localhost:2062/ServiceVector2?wsdl")
public class ServiceVector2Service
    extends Service
{

    private static final URL SERVICEVECTOR2SERVICE_WSDL_LOCATION;
    private static final WebServiceException SERVICEVECTOR2SERVICE_EXCEPTION;
    private static final QName SERVICEVECTOR2SERVICE_QNAME = new QName("http://servicevector2/", "ServiceVector2Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:2062/ServiceVector2?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEVECTOR2SERVICE_WSDL_LOCATION = url;
        SERVICEVECTOR2SERVICE_EXCEPTION = e;
    }

    public ServiceVector2Service() {
        super(__getWsdlLocation(), SERVICEVECTOR2SERVICE_QNAME);
    }

    public ServiceVector2Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEVECTOR2SERVICE_QNAME, features);
    }

    public ServiceVector2Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICEVECTOR2SERVICE_QNAME);
    }

    public ServiceVector2Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEVECTOR2SERVICE_QNAME, features);
    }

    public ServiceVector2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceVector2Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServiceVector2
     */
    @WebEndpoint(name = "ServiceVector2Port")
    public IServiceVector2 getServiceVector2Port() {
        return super.getPort(new QName("http://servicevector2/", "ServiceVector2Port"), IServiceVector2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiceVector2
     */
    @WebEndpoint(name = "ServiceVector2Port")
    public IServiceVector2 getServiceVector2Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicevector2/", "ServiceVector2Port"), IServiceVector2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEVECTOR2SERVICE_EXCEPTION!= null) {
            throw SERVICEVECTOR2SERVICE_EXCEPTION;
        }
        return SERVICEVECTOR2SERVICE_WSDL_LOCATION;
    }

}
